# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFacultybecomefaculty():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_facultybecomefaculty(self):
    self.driver.get("http://localhost/elearn/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > .external").click()
    self.driver.find_element(By.ID, "fname").click()
    self.driver.find_element(By.ID, "fname").send_keys("Example")
    self.driver.find_element(By.ID, "lname").click()
    self.driver.find_element(By.ID, "lname").send_keys("Test")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("parinmistry789@gmail.com")
    self.driver.find_element(By.ID, "age").click()
    self.driver.find_element(By.ID, "age").send_keys("40")
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(4)").click()
    self.driver.find_element(By.ID, "qualify").click()
    self.driver.find_element(By.ID, "qualify").send_keys("B.E")
    self.driver.find_element(By.ID, "experience").click()
    self.driver.find_element(By.ID, "experience").send_keys("5 years")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("7874094425")
    self.driver.find_element(By.ID, "female").click()
    self.driver.find_element(By.ID, "re-password").click()
    self.driver.find_element(By.ID, "re-password").send_keys("exampletest")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("exampletest")
    self.driver.find_element(By.NAME, "submit").click()
  
