# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStudentlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentlogin(self):
    self.driver.get("http://localhost/elearn/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) > .external").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("ghanist@gnu.ac.in")
    self.driver.find_element(By.NAME, "pass").click()
    self.driver.find_element(By.NAME, "pass").send_keys("parinmistry789")
    self.driver.find_element(By.ID, "signin").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) p").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) p").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(4) p").click()
  
