# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContactus():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contactus(self):
    self.driver.get("http://localhost/elearn/")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #name").send_keys("Parin Mistry")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #email").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 #email").send_keys("parinmistry789@gmail.com")
    self.driver.find_element(By.ID, "message").click()
    self.driver.find_element(By.ID, "message").send_keys("Feedback is good for website!")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-6 > #contact #form-submit").click()
  
