# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStudentregister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentregister(self):
    self.driver.get("http://localhost/elearn/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(7) > .external").click()
    self.driver.find_element(By.LINK_TEXT, "Sign Up").click()
    self.driver.find_element(By.ID, "fname").click()
    self.driver.find_element(By.ID, "fname").send_keys("Parin")
    self.driver.find_element(By.ID, "lname").click()
    self.driver.find_element(By.ID, "lname").send_keys("Mistry")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("parinmistry789@gmail.com")
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("8888777744")
    self.driver.find_element(By.ID, "male").click()
    self.driver.find_element(By.ID, "re-password").click()
    self.driver.find_element(By.ID, "re-password").send_keys("parin")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("parin")
    self.driver.find_element(By.NAME, "submit").click()
  
