# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


  def setup_method():
    driver= webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    driver.quit()
  
  def test_facultylogin(self):
    driver.get("http://localhost/elearn/")
    driver.set_window_size(1536, 824)
    driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > .external").click()
    driver.find_element(By.NAME, "email").click()
    driver.find_element(By.NAME, "email").send_keys("parinmistry789@gmail.com")
    driver.find_element(By.NAME, "pass").click()
    driver.find_element(By.NAME, "pass").send_keys("parinmistry789")
    driver.find_element(By.NAME, "pass").send_keys(Keys.ENTER)
    driver.find_element(By.CSS_SELECTOR, ".head").click()
    assert driver.find_element(By.CSS_SELECTOR, ".head").text == "MINDWAVE"
  
